packages:
  - ./
  - playground/
patchedDependencies:
  "@nuxt/module-builder": patches/@nuxt__module-builder.patch
allowUnusedPatches: true
settings:
  cleanupUnusedCatalogs: false
  catalogMode: strict
catalog:
  "@alanscodelog/eslint-config": ^6.3.0
  "@alanscodelog/semantic-release-config": ^5.0.4
  "@alanscodelog/tsconfigs": ^6.2.0
  "@alanscodelog/utils": ^6.0.1
  "@nuxt/eslint-config": ^1.9.0
  "@nuxt/kit": ^4.0.3
  "@nuxt/module-builder": ^1.0.2
  "@nuxt/schema": ^4.0.3
  "@nuxt/test-utils": ^3.19.2
  changelogen: ^0.6.2
  electron: ^34.5.8
  eslint: ^9.34.0
  husky: ^9.1.7
  nuxt: ^4.0.3
  pino: ^9.9.0
  pino-pretty: ^11.3.0
  semantic-release: ^24.2.8
  typescript: ^5.9.2
  vitest: ^3.2.4
  vue-tsc: ^2.2.12
